FROM php:8.2-fpm

# Set working directory
WORKDIR /var/www

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    libicu-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip intl

# Install Redis extension
RUN pecl install redis && docker-php-ext-enable redis

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u 1000 -d /home/nq57 nq57
RUN mkdir -p /home/nq57/.composer && \
    chown -R nq57:nq57 /home/nq57

# Copy existing application directory permissions
COPY --chown=nq57:nq57 . /var/www

# Change current user to nq57
USER nq57

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
